### ISSUE TITLE
Compiling under CMSSW_5_3_X broken since commit 7ece9bf8

### ISSUE THREAD

**Issue by frmeier** [Bmm4/Bmm#4]
I tried to test the instructions on https://twiki.cern.ch/twiki/bin/view/CMS/Bmm4HowtoAnalyze and did so in `CMSSW_5_3_22_patch1`, what I found to be the latest available release on t3.unl.edu. Unfortunately the last command `scramv1 b -j8` failed with output as follows:

```
----- snip ----
>> Compiling edm plugin /home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/plugins/HFDumpGenerator.cc 
/home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/src/HFDumpUtilities.cc: In function 'void fillAnaTrack(TAnaTrack*, const reco::Track&, int, int, const VertexCollection*, const MuonCollection*, const reco::BeamSpot*)':
/home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/src/HFDumpUtilities.cc:198:34: error: 'TRACK_HITS' is not a member of 'reco::HitPattern'
/home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/src/HFDumpUtilities.cc:201:36: error: 'TRACK_HITS' is not a member of 'reco::HitPattern'
>> Compiling edm plugin /home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/plugins/HFDumpMuons.cc 
>> Compiling edm plugin /home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/plugins/HFDumpPhotons.cc 
>> Compiling edm plugin /home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/plugins/HFDumpStuff.cc 
gmake: *** [tmp/slc5_amd64_gcc462/src/Bmm/CmsswAnalysis/src/BmmCmsswAnalysis/HFDumpUtilities.o] Error 1
gmake: *** Waiting for unfinished jobs....
/home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/plugins/HFDumpMuons.cc: In member function 'void HFDumpMuons::fillMuon(const reco::Muon&, int)':
/home/dominguez/frmeier/CMSSW_5_3_22_patch1/src/Bmm/CmsswAnalysis/plugins/HFDumpMuons.cc:223:69: error: 'MISSING_OUTER_HITS' is not a member of 'reco::HitPattern'
gmake: *** [tmp/slc5_amd64_gcc462/src/Bmm/CmsswAnalysis/plugins/BmmCmsswAnalysisPlugins/HFDumpMuons.o] Error 1
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```

With `git blame HFDumpUtilities.cc` I identified commit 7ece9bf8 as culprit. Reverting it using

`git revert 7ece9bf8`

Did the trick. I did not commit such a change, I only did it locally to test.
**But:** What to do? Do we need to support 5_3_X? If yes, then likely we'll need a separate branch. If not, then forget about.

**Comment by heistera** [comment]
Hello,
I have added a new parameter to the cuts file:
DSNAME - the data set name, e.g. Charmonium.
If not specified the default �Charmonium� is used.

Now in CandAna::triggerSelection() only those triggers are considered 
which are in the corresponding data set.

Best regards,
Danek

**Comment by dkotlins** [comment]
Sorry, wrong list!
Danek

On 11 Sep 2015, at 12:07, heistera <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,
I have added a new parameter to the cuts file:
DSNAME - the data set name, e.g. Charmonium.
If not specified the default �Charmonium� is used.

Now in CandAna::triggerSelection() only those triggers are considered
which are in the corresponding data set.

Best regards,
Danek
